apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
namespace: default
images:
  - name: 637423532390.dkr.ecr.us-east-1.amazonaws.com/alpinehelloworld
    newTag: "1.1"
